default: &default
  adapter: postgresql
  host: database
  username: postgres
  pool: 5

development:
  <<: *default
  database: sento_kanban_development

test:
  <<: *default
  database: sento_kanban_test
