# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

services:
  - elasticsearch

install: echo 'Nothing to install, we are using Docker :)'

before_script:
  - cp docker-compose.travis.yml docker-compose.yml

script:
  - docker-compose run web bundle exec rake db:drop db:create db:setup RAILS_ENV=test
  - docker-compose logs elasticsearch
  - docker-compose run web bundle exec rake RAILS_ENV=test
