# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

install: echo 'Nothing to install, we are using Docker :)'

script:
  - docker-compose run web bundle exec rake db:drop db:create db:setup RAILS_ENV=test
  - docker ps
  - docker-compose ps
  - docker-compose run web ping -c 2 searchengine
  - docker-compose ps
  - docker-compose run web curl http://searchengine:9200
  - docker-compose run web curl http://searchengine:9201
  - docker-compose run web bundle exec rake RAILS_ENV=test
