# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

services:
  - elasticsearch

install: echo 'Nothing to install, we are using Docker :)'

before_script:
  - sudo sysctl -w vm.max_map_count=262144
  - sudo service elasticsearch restart
  - cp docker-compose.travis.yml docker-compose.yml

script:
  - docker-compose run web bundle exec rake db:drop db:create db:setup RAILS_ENV=test
  - docker-compose run web bundle exec rake RAILS_ENV=test
