version: '2'

services:
  database:
    image: postgres
  elasticsearch:
    image: elasticsearch:5.1.1
  web:
    build: .
    command: rails s -b 0.0.0.0
    environment:
      - RACK_ENV=test
      - SECRET_KEY_BASE
    image: sento/kanban
    volumes:
      - .:/application
    links:
      - database
      - elasticsearch
